### ISSUE TITLE
What model does a human written signature get categorized into?

### ISSUE THREAD

**Issue by xtrycatchx** [SecureIdentityAlliance/osia#26]
Currently, the BiometricData can hold a biometricType of a FACE, FINGER, PALM, IRIS and an UNKNOWN.
For a citizen written signature, will it be part of this BiometricData model as well? will it be under type UNKNOWN?
Or is there a need to support for this type of object/property in an identity?

**Comment by olivier-heurtier-idemia** [comment]
Next version will clarify that and add the SIGNATURE in biometricType.
Thanks for raising the point.
