### ISSUE TITLE
Biometric services - contradiction in response policies?

### ISSUE THREAD

**Issue by SSchipp** [SecureIdentityAlliance/osia#52]
In chapter 5.6 Biometrics it reads:

> About synchronous and asynchronous processing
> Some services can be very slow depending on the algorithm used, the system workload, etc. Services are described so that:
> 

> - If possible, the answer is provided synchronously in the response of the service.

> - If not possible for some reason, a status PENDING is returned and the answer, when available, is pushed to a callback provided by the client.
>
> - If no callback is provided, this indicates that the client wants a synchronous answer, whatever the time it takes.
> 
> - If a callback is provided, this indicates that the client wants an asynchronous answer, even if the result is immediately available.

Isn't that contradictory? 
The first 2 bullet points imply, the decision whether to respond synchronously or asynchronously is made by the service (as long as a callback is provided).
Bullet point 3 is obvious. If no callback is provided, an asynchronous response is not possible. So this is already restricting the decision making of the service somewhat.
Bullet point 4 then removes even the last option for the service to adapt the response behaviour to computational necessities, placing all control of the response behaviour with the client. Bullet point 4 therefore seems to be completely contradicting bullet point 1.
Could you please clarify?

**Comment by olivier-heurtier-idemia** [comment]
Hi @SSchipp 

Thanks for your question.
This topic has been recently discussed within OSIA as there were indeed some hesitation between the two strategies. Bullet 4 was updated accordingly to make it clear that only the presence of the callback is now controlling if the response is synchronous or asynchronous.
Your comment is valid and I will also rephrase bullet 1 and 2 to avoid any ambiguity.
Thanks again for pointing that out.

**Comment by olivier-heurtier-sia** [comment]
Fixed in OSIA 6.0
